apiVersion: v1
kind: ServiceAccount
metadata:
  name: site-delivery
  namespace: site-saletesincere
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: site-delivery
  namespace: site-saletesincere
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: [site-saletesincere, site-saletesincere-staging]
    verbs: [get, patch]
  - apiGroups: ['']
    resources: [pods, resourcequotas]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: site-delivery
  namespace: site-saletesincere
subjects:
  - kind: ServiceAccount
    name: site-delivery
    namespace: site-saletesincere
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: site-delivery
---
apiVersion: v1
kind: Secret
metadata:
  name: site-delivery-token
  namespace: site-saletesincere
  annotations:
    kubernetes.io/service-account.name: site-delivery
type: kubernetes.io/service-account-token
