apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-saletesincere
resources:
  - namespace.yaml
  - quota.yaml
  - postgres.yaml
  - app.yaml
  - middleware.yaml
  - certificate.yaml
  - certificate-production.yaml
  - ingress.yaml
  - ingress-production.yaml
  - network-policies.yaml
