apiVersion: v1
kind: ResourceQuota
metadata:
  name: site-saletesincere
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "5"
    limits.memory: 6Gi
    persistentvolumeclaims: "2"
    requests.storage: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: site-saletesincere
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
