apiVersion: v1
kind: ResourceQuota
metadata:
  name: site-saletesincere
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 768Mi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "1"
    requests.storage: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: site-saletesincere
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
